---
name: Push artifacts to package.cosmian.com

on:
  workflow_call:
    inputs:
      destination:
        required: true
        type: string
      archive-name:
        required: true
        type: string
      toolchain:
        required: true
        type: string

jobs:
  build-ui:
    name: download ui
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Checkout reusable_scripts repo
        uses: actions/checkout@v4
        with:
          repository: Cosmian/reusable_scripts
          path: Cosmian/reusable_scripts
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ inputs.toolchain }}
          components: rustfmt, clippy
      - name: build ui
        run: |
          bash .github/scripts/build_ui.sh
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.archive-name }}
          path: |
            ui
            !ui/node*
          retention-days: 1
          if-no-files-found: error

  push-ui-to-package:
    needs: build-ui
    runs-on: [self-hosted, not-sgx]
    container:
      image: cosmian/docker_doc_ci
      volumes:
        - /home/cosmian/.ssh/id_rsa:/root/.ssh/id_rsa

    steps:
      - run: rm -rf ui*
      - uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.archive-name }}
      - run: find .
      - name: Creating zip to be attached to release
        shell: bash
        run: |
          set -xe
          apt update -y
          apt-get install -y zip
          zip -r ${{ inputs.archive-name }}.zip dist/
      - name: Push to package.cosmian.com
        shell: bash
        run: |
          set -ex
          if [[ "${GITHUB_REF}" =~ 'refs/tags/' ]]; then
            BRANCH="${GITHUB_REF_NAME}"
          else
            BRANCH="last_build/${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}"
          fi
          DESTINATION_DIR=/mnt/package/${{ inputs.destination }}/$BRANCH

          scp -o 'StrictHostKeyChecking no' -i /root/.ssh/id_rsa ui.zip cosmian@package.cosmian.com:$DESTINATION_DIR/
