---
name: Release and cargo publish

on:
  workflow_call:
    inputs:
      toolchain:
        required: true
        type: string
      publish:
        required: false
        default: true
        type: boolean
    secrets:
      token:
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Dump context for debug
        uses: crazy-max/ghaction-dump-context@v1

      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Publishing - dry run
        if: inputs.publish == false
        run: |
          cargo +{{ inputs.toolchain }} publish --dry-run

      - name: Publishing
        if: inputs.publish == true
        run: |
          cargo +{{ inputs.toolchain }} publish --token ${{ secrets.token }}

      - name: Release
        if: inputs.publish == true
        uses: softprops/action-gh-release@v1
