---
name: Release and cargo publish

on:
  workflow_call:
    inputs:
      toolchain:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Dump context for debug
        uses: crazy-max/ghaction-dump-context@v1

      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Publishing - dry run
        run: |
          cargo +${{ inputs.toolchain }} publish --dry-run --workspace -Z package-workspace

      - name: Publishing
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          cargo +${{ inputs.toolchain }} publish --workspace --token ${{ secrets.token }} -Z package-workspace

      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
