---
name: Cargo deny

on:
  workflow_call:
    inputs:
      toolchain:
        required: true
        type: string

jobs:
  audit:
    name: audit
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install latest cargo-deny
        run: |
          cargo install --locked cargo-deny || echo "Failed to install cargo-deny"
          cargo deny --version

      - name: Run cargo-deny check
        run: |
          cargo deny --log-level warn --all-features check
        continue-on-error: false
