---
name: Release and cargo publish

on:
  workflow_call:
    inputs:
      toolchain:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Dump context for debug
        uses: crazy-max/ghaction-dump-context@v1

      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Publishing - dry run
        shell: bash
        run: |
          if [[ "${{ inputs.toolchain }}" == *nightly* ]]; then
            TOOLCHAIN="${{ inputs.toolchain }}"
          else
            TOOLCHAIN="nightly-2025-03-31"
          fi
          cargo +$TOOLCHAIN publish --dry-run --workspace -Z package-workspace

      - name: Publishing
        if: startsWith(github.ref, 'refs/tags/')
        shell: bash
        run: |
          if [[ "${{ inputs.toolchain }}" == *nightly* ]]; then
            TOOLCHAIN="${{ inputs.toolchain }}"
          else
            TOOLCHAIN="nightly-2025-03-31"
          fi
          cargo +$TOOLCHAIN publish --workspace --token ${{ secrets.token }} -Z package-workspace

      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
