---
name: Cargo semver

on:
  workflow_call:
    inputs:
      toolchain:
        required: true
        type: string

jobs:
  semver:
    name: check semver
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up cargo cache
        uses: actions/cache@v3
        id: github-cache
        continue-on-error: false
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-semver-
          restore-keys: ${{ runner.os }}-cargo-semver-

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ inputs.toolchain }}

      - name: Install semver
        if: steps.github-cache.outputs.cache-hit != 'true'
        run: cargo +${{ inputs.toolchain }} install --version 0.44.0 --locked cargo-semver-checks

      - name: Verify semver integrity
        run: cargo +${{ inputs.toolchain }} semver-checks check-release --baseline-root=. --all-features
