---
name: Cargo deny

on:
  workflow_call:
    inputs:
      toolchain:
        required: true
        type: string

jobs:
  audit:
    name: Audit
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: EmbarkStudios/cargo-deny-action@v2
