---
name: Cargo lint

on:
  workflow_call:
    inputs:
      toolchain:
        required: true
        type: string
      prerequisites:
        required: false
        type: string
      targets:
        required: false
        type: string
        default: x86_64-unknown-linux-gnu

env:
  EXTERNAL_OPENSSL_DIR: /usr/local/openssl

jobs:
  clippy:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Cache dependencies
        id: cargo_cache
        uses: Swatinem/rust-cache@v2
        with:
          key: ${{ runner.os }}

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ inputs.toolchain }}
          components: rustfmt, clippy
          targets: ${{ inputs.targets || 'x86_64-unknown-linux-gnu' }}

      - name: Prerequisites
        if: ${{ inputs.prerequisites }}
        run: |
          set -ex
          ${{ inputs.prerequisites }}

      # Ensure all code has been formatted with rustfmt
      - name: Check formatting
        run: cargo +${{ inputs.toolchain }} fmt --all -- --check --color always

      - name: Static analysis
        run: cargo clippy --workspace --all-targets -- -D warnings
        env:
          OPENSSL_DIR: ${{ env.OPENSSL_DIR }}

      - name: Static analysis all features
        run: cargo clippy --workspace --all-targets --all-features -- -D warnings
        env:
          OPENSSL_DIR: ${{ env.OPENSSL_DIR }}
