---
name: Push artifacts to package.cosmian.com

on:
  workflow_call:
    inputs:
      project-name:
        required: true
        type: string
      archive-name:
        required: true
        type: string
      artifacts-name:
        required: true
        type: string

jobs:
  ##############################################################################
  ### Packages
  ##############################################################################
  packages:
    name: push ${{ inputs.archive-name }} to package.cosmian.com
    runs-on: [self-hosted, not-sgx]

    steps:
      - uses: actions/download-artifact@v4
      - run: find .

      - name: Creating zip to be attached to release
        run: |
          set -x
          sudo apt-get install -y zip
          rm -f ${{ inputs.archive-name }}.zip
          zip -r ${{ inputs.archive-name }} ${{ inputs.artifacts-name }}

      - name: Push to package.cosmian.com
        run: |
          set -x
          DESTINATION_DIR=/mnt/package/${{ inputs.project-name }}/last_build/${{ github.head_ref }}
          ssh -vvv cosmian@package.cosmian.com mkdir -p $DESTINATION_DIR
          scp ${{ inputs.archive-name }} cosmian@package.cosmian.com:$DESTINATION_DIR/

      - name: Push to package.cosmian.com - tags
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          set -x
          DESTINATION_DIR=/mnt/package/${{ inputs.project-name }}/$VERSION
          ssh cosmian@package.cosmian.com mkdir -p $DESTINATION_DIR
          scp ${{ inputs.archive-name }} cosmian@package.cosmian.com:$DESTINATION_DIR/
        env:
          VERSION: ${{ github.ref_name }}
