---
name: Push artifacts to package.cosmian.com

on:
  workflow_call:
    inputs:
      project-name:
        required: true
        type: string
      archive-name:
        required: true
        type: string
      artifacts-name:
        required: true
        type: string

jobs:
  ##############################################################################
  ### Packages
  ##############################################################################
  packages:
    name: push to package.cosmian.com
    runs-on: self-hosted

    steps:
      - uses: actions/download-artifact@v3
      - run: find .

      - name: Creating zip to be attached to release
        run: |
          sudo apt-get install -y zip
          zip -r ${{ inputs.archive-name }} ${{ inputs.artifacts-name }}

      - name: Push to package.cosmian.com
        run: |
          set -x
          echo "$PACKAGE_SSH_KEY" > ~/id_rsa
          chmod 600 ~/id_rsa
          DESTINATION_DIR=/mnt/package/${{ inputs.project-name }}/last_build/${{ github.head_ref }}
          ssh -i ~/id_rsa cosmian@package.cosmian.com mkdir -p $DESTINATION_DIR
          scp -i ~/id_rsa ${{ inputs.archive-name }} cosmian@package.cosmian.com:$DESTINATION_DIR/
          rm ~/id_rsa
        env:
          PACKAGE_SSH_KEY: ${{ secrets.PACKAGE_SSH_KEY }}

      - name: Push to package.cosmian.com - tags
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          set -x
          echo "$PACKAGE_SSH_KEY" > ~/id_rsa
          chmod 600 ~/id_rsa
          DESTINATION_DIR=/mnt/package/${{ inputs.project-name }}/$VERSION
          ssh -i ~/id_rsa cosmian@package.cosmian.com mkdir -p $DESTINATION_DIR
          scp -i ~/id_rsa ${{ inputs.archive-name }} cosmian@package.cosmian.com:$DESTINATION_DIR/
          rm ~/id_rsa
        env:
          PACKAGE_SSH_KEY: ${{ secrets.PACKAGE_SSH_KEY }}
          VERSION: ${{ github.ref_name }}
